#include "itm/app/telemetry_catalog.h"

/* Provisional values. Replace only after the source ICDs and RET ICD exist. */
const itm_signal_metadata_t itm_telemetry_catalog[ITM_SIGNAL_COUNT] = {
    {ITM_SIGNAL_AV_BATT_VOLTAGE, ITM_SIGNAL_TYPE_U32, ITM_UNIT_VOLT,
     ITM_SOURCE_AV_BATT, -3, 0, 40000, 1000U},
    {ITM_SIGNAL_AV_BATT_SOC, ITM_SIGNAL_TYPE_U32, ITM_UNIT_PERCENT,
     ITM_SOURCE_AV_BATT, -2, 0, 10000, 1000U},
    {ITM_SIGNAL_ACT_BATT_VOLTAGE, ITM_SIGNAL_TYPE_U32, ITM_UNIT_VOLT,
     ITM_SOURCE_ACT_BATT, -3, 0, 200000, 1000U},
    {ITM_SIGNAL_ACT_BATT_SOC, ITM_SIGNAL_TYPE_U32, ITM_UNIT_PERCENT,
     ITM_SOURCE_ACT_BATT, -2, 0, 10000, 1000U},
    {ITM_SIGNAL_CEB_TEMPERATURE, ITM_SIGNAL_TYPE_I32, ITM_UNIT_CELSIUS,
     ITM_SOURCE_CEB, -2, -5000, 15000, 500U},
    {ITM_SIGNAL_CEB_STATUS, ITM_SIGNAL_TYPE_U32, ITM_UNIT_STATE,
     ITM_SOURCE_CEB, 0, 0, 0xFFFF, 500U},
    {ITM_SIGNAL_CB_STATE, ITM_SIGNAL_TYPE_BOOL, ITM_UNIT_STATE,
     ITM_SOURCE_CB, 0, 0, 1, 100U},
    {ITM_SIGNAL_CB_FAULT, ITM_SIGNAL_TYPE_BOOL, ITM_UNIT_STATE,
     ITM_SOURCE_CB, 0, 0, 1, 100U},
};
