#!/usr/bin/env python3
"""Generate deterministic C codec and audit report from Battery.dbc."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import pathlib
import re
import subprocess
import sys
import tempfile

EXPECTED_CANTOOLS = "41.0.2"


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalize_generated(path: pathlib.Path) -> None:
    text = path.read_text(encoding="utf-8")
    text = re.sub(
        r"generated by cantools version 41\.0\.2 .*\.\n",
        "generated by cantools version 41.0.2 (deterministic build).\n",
        text,
        count=1,
    )
    path.write_text(text, encoding="utf-8", newline="\n")


def generate(dbc: pathlib.Path, output: pathlib.Path) -> None:
    version = importlib.metadata.version("cantools")
    if version != EXPECTED_CANTOOLS:
        raise SystemExit(f"cantools {EXPECTED_CANTOOLS} required, found {version}")
    output.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [sys.executable, "-m", "cantools", "generate_c_source", "--use-float",
         "--database-name", "battery_dbc_generated", "--output-directory",
         str(output), str(dbc)], check=True
    )
    for name in ("battery_dbc_generated.c", "battery_dbc_generated.h"):
        normalize_generated(output / name)

    import cantools
    database = cantools.database.load_file(dbc, strict=True)
    report = {
        "source": "config/can/Battery.dbc",
        "dbc_sha256": sha256(dbc),
        "cantools_version": version,
        "generator_command": (
            "python tools/generate_battery_dbc.py --write"
        ),
        "messages": [],
        "reference_vectors": [
            {
                "message": "CAN_PACKET_BMS_V_TOT",
                "data_hex": "41e400000000001e",
                "decoded_by_cantools": database.decode_message(
                    0x260A, bytes.fromhex("41e400000000001e"),
                    decode_choices=False),
            },
            {
                "message": "CAN_PACKET_BMS_SOC_SOH_TEMP_STAT",
                "data_hex": "0ce4100480ff2aa5",
                "decoded_by_cantools": database.decode_message(
                    0x2D0A, bytes.fromhex("0ce4100480ff2aa5"),
                    decode_choices=False),
            },
        ],
    }
    for message in database.messages:
        report["messages"].append({
            "name": message.name,
            "frame_id": f"0x{message.frame_id:X}",
            "extended": message.is_extended_frame,
            "length": message.length,
            "senders": list(message.senders),
            "signals": [{
                "name": signal.name,
                "start": signal.start,
                "length": signal.length,
                "byte_order": signal.byte_order,
                "signed": signal.is_signed,
                "scale": str(signal.scale),
                "offset": str(signal.offset),
                "minimum": None if signal.minimum is None else str(signal.minimum),
                "maximum": None if signal.maximum is None else str(signal.maximum),
                "unit": signal.unit,
                "raw_type": "float32" if signal.is_float else "integer",
                "receivers": list(signal.receivers),
            } for signal in message.signals],
        })
    (output / "battery_dbc_audit.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8", newline="\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parents[1]
    dbc = root / "config/can/Battery.dbc"
    destination = root / "generated/can"
    if args.write:
        generate(dbc, destination)
        return 0
    with tempfile.TemporaryDirectory() as directory:
        temporary = pathlib.Path(directory)
        generate(dbc, temporary)
        expected = {path.name: path.read_bytes() for path in temporary.iterdir()}
        actual = {path.name: path.read_bytes() for path in destination.iterdir()}
        if expected != actual:
            print("Generated DBCC files are stale; run with --write.", file=sys.stderr)
            return 1
    print("Generated DBCC files match Battery.dbc.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
